initContainer:
  extraArgs:
    - --loggingFormat=json

extraArgs:
  - --loggingFormat=json
  - --enablePolicyException
  - --exceptionNamespace=kyverno

cleanupController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - ''
          resources:
            - pods
