# -- Resources to install
resources:
  clusterpolicyreports: true
  policyreports: true

# -- Additional CRDs annotations
annotations: {}
  # argocd.argoproj.io/sync-options: Replace=true
  # strategy.spinnaker.io/replace: 'true'

# -- Additional CRDs labels
labels: {}
