apiVersion: v2
name: kyverno-lib
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
home: https://kyverno.github.io/kyverno-envoy-plugin

type: library
version: 0.0.0
appVersion: latest
kubeVersion: ">=1.25.0-0"
