name: helm-test

on:
  pull_request:
    branches:
      - main
      - release*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
      - name: Run helm test
        uses: ./.github/actions/helm-test
