name: image
on:
  push:
    branches:
      - 'main'
      - 'release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write 

jobs:
  push-init-kyverno:
    uses: ./.github/workflows/reuse-v2.yaml
    with:
      makefile-target: ko-publish-kyvernopre-dev
      sign-image: false
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno:
    uses: ./.github/workflows/reuse-v2.yaml
    with:
      publish_command: ko-publish-kyverno-dev
      sign-image: false
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-cleanup-controller:
    uses: ./.github/workflows/reuse-v2.yaml
    with:
      publish_command: ko-publish-cleanup-controller-dev
      sign-image: false
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno-cli:
    uses: ./.github/workflows/reuse-v2.yaml
    with:
      publish_command: ko-publish-cli-dev
      sign-image: false
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}
